apiVersion: v1
kind: Pod
metadata: 
  labels: 
    pod: app 
    server: tomcat 
  name: podapp    ## name of the pod 
spec: 
  containers: 
   - image: tomcat:8 
     name: appserver  ## name of the container 
     ports: 
     - containerPort: 8080 
       protocol: TCP 
       name: appport  
   - image: nginx 
     name: webserver
     ports: 
     - containerPort: 80 
       protocol: TCP 
       name: webport 
      